drest/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('restaurante/', include('restaurante.urls')),
]

restaurante/urls.py
from django.urls import path

from restaurante.views import *

app_name = 'restaurant'
urlpatterns = [
    path('clients/', ListClientView.as_view(), name='clients'),
    path('clients/create_client', CreateClientView.as_view(), name='create_client'),
    path('clients/edit_client/<int:pk>', UpdateClientView.as_view(), name='edit_client'),
    path('clients/delete_client/<int:pk>', DeleteClientView.as_view(), name='delete_client'),
    path('products/', ListProductView.as_view(), name='products'),
    path('products/create_product', CreateProductView.as_view(), name='create_product'),
    path('products/edit_product/<int:pk>', UpdateProductView.as_view(), name='edit_product'),
    path('products/delete_product/<int:pk>', DeleteProductView.as_view(), name='delete_product'),
    path('waiters/', ListWaiterView.as_view(), name='waiters'),
    path('waiters/create_waiter', CreateWaiterView.as_view(), name='create_waiter'),
    path('waiters/edit_waiter/<int:pk>', UpdateWaiterView.as_view(), name='edit_waiter'),
    path('waiters/delete_waiter/<int:pk>', DeleteWaiterView.as_view(), name='delete_waiter'),
    path('tables/', ListTableView.as_view(), name='tables'),
    path('tables/create_table', CreateTableView.as_view(), name='create_table'),
    path('tables/edit_table/<int:pk>', UpdateTableView.as_view(), name='edit_table'),
    path('tables/delete_table/<int:pk>', DeleteTableView.as_view(), name='delete_table'),
    path('orders/', ListOrderView.as_view(), name='orders'),
    path('orders/create_order', CreateOrderView.as_view(), name='create_order'),
    path('orders/edit_order/<int:pk>', UpdateOrderView.as_view(), name='edit_order'),
    path('orders/delete_order/<int:pk>', DeleteOrderView.as_view(), name='delete_order'),
    path('invoices/', ListInvoiceView.as_view(), name='invoices'),
    path('invoices/create_invoice', CreateInvoiceView.as_view(), name='create_invoice'),
    path('invoices/edit_invoice/<int:pk>', UpdateInvoiceView.as_view(), name='edit_invoice'),
    path('invoices/delete_invoice/<int:pk>', DeleteInvoiceView.as_view(), name='delete_invoice'),

]

restaurante/models.py
from django.db import models


# Create your models here.

class Client(models.Model):
    name = models.CharField(max_length=45)
    lastname = models.CharField(max_length=45)
    email = models.EmailField(max_length=45)
    phone = models.CharField(max_length=45)
    address = models.CharField(max_length=45)
    observations = models.CharField(max_length=45, null=True, blank=True)

    def __str__(self):
        return self.name + ' ' + self.lastname


class Waiter(models.Model):
    name = models.CharField(max_length=45)
    first_lastname = models.CharField(max_length=45)
    second_lastname = models.CharField(max_length=45)

    def __str__(self):
        return self.name


class Product(models.Model):
    CHOICE_TYPE = (
        ('saucer', 'Saucer'),
        ('drink', 'Drink'),
    )
    name = models.CharField(max_length=45)
    type = models.CharField(max_length=10, choices=CHOICE_TYPE)
    amount = models.FloatField()

    def __str__(self):
        return self.name


class Table(models.Model):
    number_diners = models.IntegerField()
    location = models.CharField(max_length=45)

    def __str__(self):
        return self.location


class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.name


class Invoice(models.Model):
    date_invoice = models.DateField(auto_now=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    waiter = models.ForeignKey(Waiter, on_delete=models.CASCADE)
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    orders = models.ManyToManyField(Order)

restaurante/forms.py
from django import forms

from restaurante.models import Client, Product, Waiter, Table, Order, Invoice


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'lastname', 'email', 'phone', 'address', 'observations')

    name = forms.CharField(max_length=100,
                           widget=forms.TextInput(attrs={'class': 'form-control my-2', 'placeholder': 'Name'}))
    lastname = forms.CharField(max_length=100,
                               widget=forms.TextInput(attrs={'class': 'form-control my-2', 'placeholder': 'Lastname'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control my-2', 'placeholder': 'Email'}))
    phone = forms.CharField(max_length=100,
                            widget=forms.TextInput(attrs={'class': 'form-control my-2', 'placeholder': 'Phone'}))
    address = forms.CharField(max_length=100,
                              widget=forms.TextInput(attrs={'class': 'form-control my-2', 'placeholder': 'Address'}))
    observations = forms.CharField(max_length=100,
                                   widget=forms.TextInput(
                                       attrs={'class': 'form-control my-2', 'placeholder': 'Observations'}))


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'type', 'amount')

    name = forms.CharField(max_length=100,
                           widget=forms.TextInput(attrs={'class': 'form-control my-2', 'placeholder': 'Name'}))
    type = forms.ChoiceField(choices=Product.CHOICE_TYPE,
                             widget=forms.Select(attrs={'class': 'form-control my-2'}))
    amount = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control my-2', 'placeholder': 'Amount'}))


class WaiterForm(forms.ModelForm):
    class Meta:
        model = Waiter
        fields = ('name', 'first_lastname', 'second_lastname')

    name = forms.CharField(max_length=100,
                           widget=forms.TextInput(attrs={'class': 'form-control my-2', 'placeholder': 'Name'}))
    first_lastname = forms.CharField(max_length=100,
                                     widget=forms.TextInput(
                                         attrs={'class': 'form-control my-2', 'placeholder': 'First Lastname'}))
    second_lastname = forms.CharField(max_length=100,
                                      widget=forms.TextInput(
                                          attrs={'class': 'form-control my-2', 'placeholder': 'Second Lastname'}))


class TableForm(forms.ModelForm):
    class Meta:
        model = Table
        fields = ('number_diners', 'location')

    number_diners = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control my-2', 'placeholder': 'Number Diners'}))
    location = forms.CharField(max_length=100,
                               widget=forms.TextInput(attrs={'class': 'form-control my-2', 'placeholder': 'Location'}))


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('product', 'quantity')

    product = forms.ModelChoiceField(queryset=Product.objects.all(),
                                     widget=forms.Select(attrs={'class': 'form-control my-2'}))
    quantity = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control my-2', 'placeholder': 'Quantity'}))


class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = ('client', 'waiter', 'table', 'orders')

    client = forms.ModelChoiceField(queryset=Client.objects.all(),
                                    widget=forms.Select(attrs={'class': 'form-control my-2'}))
    waiter = forms.ModelChoiceField(queryset=Waiter.objects.all(),
                                    widget=forms.Select(attrs={'class': 'form-control my-2'}))
    table = forms.ModelChoiceField(queryset=Table.objects.all(),
                                   widget=forms.Select(attrs={'class': 'form-control my-2'}))
    orders = forms.ModelMultipleChoiceField(queryset=Order.objects.all(),
                                            widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-check my-2'}))

restaurante/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from restaurante.models import Client, Product, Waiter, Table, Order, Invoice
from restaurante.forms import ClientForm, ProductForm, WaiterForm, TableForm, OrderForm, InvoiceForm


class ListClientView(ListView):
    model = Client
    template_name = 'restaurante/client/index.html'
    context_object_name = 'clients'


class CreateClientView(CreateView):
    form_class = ClientForm
    template_name = 'restaurante/client/create_client.html'
    success_url = reverse_lazy('restaurant:clients')


class UpdateClientView(UpdateView):
    form_class = ClientForm
    model = Client
    template_name = 'restaurante/client/edit_client.html'
    success_url = reverse_lazy('restaurant:clients')


class DeleteClientView(DeleteView):
    model = Client
    template_name = 'restaurante/client/delete_client.html'
    success_url = reverse_lazy('restaurant:clients')


class ListProductView(ListView):
    model = Product
    template_name = 'restaurante/products/index.html'
    context_object_name = 'products'


class CreateProductView(CreateView):
    form_class = ProductForm
    template_name = 'restaurante/products/create_product.html'
    success_url = reverse_lazy('restaurant:products')


class UpdateProductView(UpdateView):
    form_class = ProductForm
    model = Product
    template_name = 'restaurante/products/edit_product.html'
    success_url = reverse_lazy('restaurant:products')


class DeleteProductView(DeleteView):
    model = Product
    template_name = 'restaurante/products/delete_product.html'
    success_url = reverse_lazy('restaurant:products')


class ListWaiterView(ListView):
    model = Waiter
    template_name = 'restaurante/waiter/index.html'
    context_object_name = 'waiters'


class CreateWaiterView(CreateView):
    form_class = WaiterForm
    template_name = 'restaurante/waiter/create_waiter.html'
    success_url = reverse_lazy('restaurant:waiters')


class UpdateWaiterView(UpdateView):
    form_class = WaiterForm
    model = Waiter
    template_name = 'restaurante/waiter/edit_waiter.html'
    success_url = reverse_lazy('restaurant:waiters')


class DeleteWaiterView(DeleteView):
    model = Waiter
    template_name = 'restaurante/waiter/delete_waiter.html'
    success_url = reverse_lazy('restaurant:waiters')


class ListTableView(ListView):
    model = Table
    template_name = 'restaurante/table/index.html'
    context_object_name = 'tables'


class CreateTableView(CreateView):
    form_class = TableForm
    template_name = 'restaurante/table/create_table.html'
    success_url = reverse_lazy('restaurant:tables')


class UpdateTableView(UpdateView):
    form_class = TableForm
    model = Table
    template_name = 'restaurante/table/edit_table.html'
    success_url = reverse_lazy('restaurant:tables')


class DeleteTableView(DeleteView):
    model = Table
    template_name = 'restaurante/table/delete_table.html'
    success_url = reverse_lazy('restaurant:tables')


class ListOrderView(ListView):
    model = Order
    template_name = 'restaurante/order/index.html'
    context_object_name = 'orders'


class CreateOrderView(CreateView):
    form_class = OrderForm
    template_name = 'restaurante/order/create_order.html'
    success_url = reverse_lazy('restaurant:orders')


class UpdateOrderView(UpdateView):
    form_class = OrderForm
    model = Order
    template_name = 'restaurante/order/edit_order.html'
    success_url = reverse_lazy('restaurant:orders')


class DeleteOrderView(DeleteView):
    model = Order
    template_name = 'restaurante/order/delete_order.html'
    success_url = reverse_lazy('restaurant:orders')


class ListInvoiceView(ListView):
    model = Invoice
    template_name = 'restaurante/invoice/index.html'
    context_object_name = 'invoices'


class CreateInvoiceView(CreateView):
    form_class = InvoiceForm
    template_name = 'restaurante/invoice/create_invoice.html'
    success_url = reverse_lazy('restaurant:invoices')


class UpdateInvoiceView(UpdateView):
    form_class = InvoiceForm
    model = Invoice
    template_name = 'restaurante/invoice/edit_invoice.html'
    success_url = reverse_lazy('restaurant:invoices')


class DeleteInvoiceView(DeleteView):
    model = Invoice
    template_name = 'restaurante/invoice/delete_invoice.html'
    success_url = reverse_lazy('restaurant:invoices')

templates/restaurante/table/create_table.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <form method="POST" action="{% url 'restaurant:create_table' %}" class="form"
              enctype="multipart/form-data">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create table</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% csrf_token %} {{ form.as_p }}
                <button class="btn btn-primary rounded-pill" type="submit"><i
                        class="bi bi-pencil-square"></i>Create
                </button>
                <a href="{% url 'restaurant:tables' %}" class="btn btn-danger rounded-pill"><span
                        class="fa fa-undo"></span>
                    Cancel</a>


            </div>
        </form>
    </div>
</div>

templates/restaurante/table/delete_table.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <form method="POST" action="{% url 'restaurant:delete_table' object.pk %}" class="form"
              enctype="multipart/form-data">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete table - {{ object.pk }} - {{ object.location }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% csrf_token %}
                <p>Are you sure you want to delete this table?</p>
                <button class="btn btn-danger rounded-pill" type="submit"><i class="bi bi-trash"></i>Delete</button>
                <a href="{% url 'restaurant:tables' %}" class="btn btn-success rounded-pill"><span
                        class="fa fa-undo"></span>
                    Cancel</a>


            </div>
        </form>
    </div>
</div>

templates/restaurante/table/edit_table.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <form method="POST" action="{% url 'restaurant:edit_table' object.pk %}" class="form"
              enctype="multipart/form-data">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit table</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% csrf_token %} {{ form.as_p }}
                <button class="btn btn-primary rounded-pill" type="submit"><i
                        class="bi bi-pencil-square"></i>Edit
                </button>
                <a href="{% url 'restaurant:tables' %}" class="btn btn-danger rounded-pill"><span
                        class="fa fa-undo"></span>
                    Cancel</a>
            </div>
        </form>
    </div>
</div>

templates/restaurante/table/index.html
{% extends 'base.html' %}
{% block title %} Tables {% endblock %}
{% block content %}
    <div class="card text-center">
        <div class="card-body">
            <h3 class="card-title text-center">Tables</h3>
            <div class="form-group text-center p-3">
                <a href="#" onclick="return open_modal('{% url 'restaurant:create_table' %}')"
                   class="btn btn-success rounded-pill" type="submit">Create</a>
            </div>
            <table class="table table-striped table-inverse table-responsive">
                <thead class="table-dark">
                <tr>
                    <th>Number of diners</th>
                    <th>Location</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for table in tables %}
                    <tr>
                        <td>{{ table.number_diners }}</td>
                        <td>{{ table.location }}</td>
                        <td>
                            <a href="#" onclick="return open_modal('{% url 'restaurant:edit_table' table.id %}')"
                               class="btn btn-warning rounded-pill" type="submit"><i
                                    class="bi bi-pencil-square"></i></a>
                            <a href="#" onclick="return open_modal('{% url 'restaurant:delete_table' table.id %}')"
                               class="btn btn-danger rounded-pill"><i class="bi bi-trash"></i></a>


                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="5">No data found.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}