drest/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('restaurante/', include('restaurante.urls')),
]

restaurante/urls.py
from django.urls import path

from restaurante.views import *

app_name = 'restaurant'
urlpatterns = [
    path('clients/', ListClientView.as_view(), name='clients'),
    path('clients/create_client', CreateClientView.as_view(), name='create_client'),
    path('clients/edit_client/<int:pk>', UpdateClientView.as_view(), name='edit_client'),
    path('clients/delete_client/<int:pk>', DeleteClientView.as_view(), name='delete_client'),
    path('products/', ListProductView.as_view(), name='products'),
    path('products/create_product', CreateProductView.as_view(), name='create_product'),
    path('products/edit_product/<int:pk>', UpdateProductView.as_view(), name='edit_product'),
    path('products/delete_product/<int:pk>', DeleteProductView.as_view(), name='delete_product'),
    path('waiters/', ListWaiterView.as_view(), name='waiters'),
    path('waiters/create_waiter', CreateWaiterView.as_view(), name='create_waiter'),
    path('waiters/edit_waiter/<int:pk>', UpdateWaiterView.as_view(), name='edit_waiter'),
    path('waiters/delete_waiter/<int:pk>', DeleteWaiterView.as_view(), name='delete_waiter'),
    path('tables/', ListTableView.as_view(), name='tables'),
    path('tables/create_table', CreateTableView.as_view(), name='create_table'),
    path('tables/edit_table/<int:pk>', UpdateTableView.as_view(), name='edit_table'),
    path('tables/delete_table/<int:pk>', DeleteTableView.as_view(), name='delete_table'),
    path('orders/', ListOrderView.as_view(), name='orders'),
    path('orders/create_order', CreateOrderView.as_view(), name='create_order'),
    path('orders/edit_order/<int:pk>', UpdateOrderView.as_view(), name='edit_order'),
    path('orders/delete_order/<int:pk>', DeleteOrderView.as_view(), name='delete_order'),
    path('invoices/', ListInvoiceView.as_view(), name='invoices'),
    path('invoices/create_invoice', CreateInvoiceView.as_view(), name='create_invoice'),
    path('invoices/edit_invoice/<int:pk>', UpdateInvoiceView.as_view(), name='edit_invoice'),
    path('invoices/delete_invoice/<int:pk>', DeleteInvoiceView.as_view(), name='delete_invoice'),

]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <title>{% block title %} Restaurante {% endblock %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS v5.0.2 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet"/>

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet"/>


</head>
<body>
<!--- Navbar -->
<nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="#">Restaurant</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'restaurant:clients' %}">Clients</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'restaurant:products' %}">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'restaurant:tables' %}">Tables</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'restaurant:waiters' %}">Waiters</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'restaurant:orders' %}">Orders</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'restaurant:invoices' %}">Invoices</a>
                </li>
            </ul>

        </div>
    </div>
</nav>


<div class="container p-3">
    <div class="row">
        <div class="col-12">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
<div id="ventana_modal" class="modal fade" role="dialog"></div>
<!-- Bootstrap JavaScript Libraries -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

<script>
    function open_modal(url) {
        $('#ventana_modal').load(url, function () {
            $(this).modal({
                backdrop: 'static',
                keyboard: false
            })
            $(this).modal('show');
        });
        return false;
    }

    function cerrar_modal() {
        $('#ventana_modal').modal('hide');
        return false;
    }


</script>
</body>
</html>